cafehero:
    system:
        password: ''
        username: ''
jwt:
    expiration: ''
    issuer: ''
    secret: ''
server:
    port: ''
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: ''
        username: ''
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false
